import crowdImage from '../assets/crowd-party.jpg';
import conference from '../assets/conference.png';
import showImage from '../assets/show-image.jpg';
export const tickets = [
  {
    id: 'ticket-1',
    title: 'PREMIUM TICKET',
    subtitle: 'Unlock premium seating, lounges, and exclusive GITEX NIGERIA workshops',
    price: 32.5,
    isFree: false,
    backgroundColor: 'from-purple-700 to-purple-900',
    backroundImage: conference,
    isExclusive: false,
    isBestSeller: false,
    showFeatures: false,
    features: [
      { text: "All Standard Benefits", isActive: true },
      { text: "Early Check-In & Reserved Seating", isActive: true },
      { text: "Access to Premium Workshops", isActive: true },
      { text: "Premium Lounge Access", isActive: true },
      { text: "Merchandise Package", isActive: true },
      { text: "Event Recordings Access", isActive: true },
    ],
    workshops: ['global-leaders-forum', 'ai-everything', 'ai-robotics', 'digital-finance', 'future-mobility'],
    services: [
      'vip-lounge',
      'priority-seating',
      'exclusive-networking',
      'early-checkin',
      'recordings-access',
      'workshop-pass',
      'meal-coupons',
      'merchandise-package',
      'photo-session'
    ],
    isServicesRequired: true,
    isWorkshopsRequired: true,
  },
  {
    id: 'ticket-2',
    title: 'STANDARD TICKET',
    subtitle: 'Entry to GITEX NIGERIA with access to common sessions and networking lounges',
    price: 10,
    isFree: false,
    backgroundColor: 'from-orange-700 to-orange-900',
    backroundImage: crowdImage,
    isExclusive: false,
    isBestSeller: false,
    showFeatures: true,
    features: [
      { text: "Access to All Conference Tracks", isActive: true },
      { text: "Networking Events", isActive: true },
      { text: "3 Days General Access", isActive: true },
      { text: "Basic Meal & Drink Vouchers", isActive: true },
      { text: "Merch Package (Lite)", isActive: true },
      { text: "Workshop Participation", isActive: true },
    ],
    workshops: ['cybersecurity', 'future-health', 'digital-cities', 'ai-everything', 'energy-transition'],
    services: ['main-hall-access', 'meal-coupons', 'merchandise-package', 'workshop-pass', 'photo-session'],
    isServicesRequired: true,
    isWorkshopsRequired: true,
    vatText: "Incl. VAT",
  },
  {
    id: 'ticket-3',
    title: 'FREE TICKET',
    subtitle: 'Basic entry to exhibition halls and selected public sessions at GITEX NIGERIA',
    price: 0,
    isFree: true,
    backgroundColor: 'from-green-700 to-green-900',
    backroundImage: showImage,
    isExclusive: true,
    isBestSeller: false,
    showFeatures: true,
    features: [
      { text: "Entry Badge", isActive: true },
      { text: "Access to Main Hall", isActive: true },
      { text: "Networking Events (Basic)", isActive: true },
      { text: "Workshop Access (Limited)", isActive: true },
      { text: "No Access to VIP Areas", isActive: false },
      { text: "No Meal Coupons", isActive: false },
    ],
    workshops: ['gitex-main-stage', 'ai-robotics', 'edtech', 'intelligent-connectivity', 'digital-finance'],
    services: ['entry-badge', 'main-hall-access', 'eco-kit', 'certificate', 'drink-vouchers'],
    isServicesRequired: true,
    isWorkshopsRequired: true,
    vatText: "Incl. VAT",
  },
  {
    id: 'ticket-4',
    title: 'STUDENT PASS',
    subtitle: 'Designed for students: access to masterclasses, lounges, and key learning tracks',
    price: 0,
    isFree: false,
    backgroundColor: 'from-red-700 to-red-900',
    backroundImage: crowdImage,
    isExclusive: false,
    isBestSeller: true,
    showFeatures: true,
    features: [
      { text: "Access to Conventions & Investor Lounge", isActive: true },
      { text: "Network Events", isActive: true },
      { text: "All Conference Tracks", isActive: true },
      { text: "All Masterclasses", isActive: true },
      { text: "3 Days Access to the Show", isActive: true },
      { text: "Access to Dubai Internet City Lounge", isActive: true },
    ],
    workshops: ['intelligent-connectivity', 'digital-finance', 'future-mobility'],
    services: ['vip-lounge', 'priority-seating', 'shuttle-service'],
    isServicesRequired: true,
    isWorkshopsRequired: true,
    vatText: "Incl. VAT",
  },
  {
    id: 'ticket-5',
    title: 'VIP TICKET',
    subtitle: 'All-access experience with backstage, meet & greet, and VIP-exclusive services',
    price: 50,
    isFree: false,
    backgroundColor: 'from-lime-600 to-green-700',
    backroundImage: crowdImage,
    isExclusive: false,
    isBestSeller: false,
    features: [
      { text: "All Premium Benefits", isActive: true },
      { text: "Meet & Greet with Speakers", isActive: true },
      { text: "Shuttle & Priority Parking", isActive: true },
      { text: "Live Translation Device", isActive: true },
      { text: "Backstage Access", isActive: true },
      { text: "Guided VIP Tour", isActive: true },
    ],
    workshops: ['global-leaders-forum', 'ai-everything', 'cybersecurity', 'future-health', 'digital-cities'],
    services: [
      'vip-lounge',
      'priority-seating',
      'shuttle-service',
      'meet-greet',
      'translation-device',
      'backstage-tour',
      'parking-pass',
      'recordings-access',
      'guided-tour',
      'photo-session',
      'priority-support',
      'charging-station-access',
      'workshop-pass',
      'meal-coupons'
    ],
    isServicesRequired: true,
    isWorkshopsRequired: true,
    vatText: "Incl. VAT",
  },
  {
    id: 'ticket-6',
    title: "ALL ACCESS PASS (3-DAY)",
    subtitle: 'Enjoy everything GITEX NIGERIA offers across 3 days – workshops, lounges, and more',
    price: 0,
    isFree: false,
    backgroundColor: 'from-blue-700 to-blue-900',
    backroundImage: showImage,
    isExclusive: false,
    isBestSeller: false,
    showFeatures: true,
    features: [
      { text: "Access to All Areas & Lounges", isActive: true },
      { text: "All Workshops Included", isActive: true },
      { text: "Event Recordings Access", isActive: true },
      { text: "Backstage + Networking Events", isActive: true },
      { text: "Photo Session + Guided Tour", isActive: true },
      { text: "Early Check-In", isActive: true },
    ],
    workshops: [
      'global-leaders-forum', 'ai-everything', 'future-health', 'gitex-main-stage',
      'cybersecurity', 'energy-transition', 'digital-cities', 'ai-robotics'
    ],
    services: [
      'vip-lounge', 'exclusive-networking', 'backstage-tour', 'recordings-access',
      'photo-session', 'guided-tour', 'priority-support', 'early-checkin', 'workshop-pass', 'charging-station-access'
    ],
    isServicesRequired: true,
    isWorkshopsRequired: true,
    vatText: "Incl. VAT",
  },
];

export const workshopOptions = [
  { value: 'global-leaders-forum', label: 'Global Leaders Forum !NEW (3 Days)' },
  { value: 'gitex-main-stage', label: 'GITEX Main Stage' },
  { value: 'ai-robotics', label: 'Artificial Intelligence & Robotics (15)' },
  { value: 'ai-everything', label: 'AI Everything (4 Days)' },
  { value: 'cybersecurity', label: 'Cybersecurity (4 Days)' },
  { value: 'future-health', label: 'Future Health !NEW (2 Days)' },
  { value: 'digital-cities', label: 'Digital Cities (1 Day)' },
  { value: 'edtech', label: 'Edtech (1 Day)' },
  { value: 'energy-transition', label: 'Energy Transition (1 Day)' },
  { value: 'intelligent-connectivity', label: 'Intelligent Connectivity (1 Day)' },
  { value: 'digital-finance', label: 'Digital Finance (1 Day)' },
  { value: 'future-mobility', label: 'Future Mobility (1 Day)' }
];

export const serviceOptions = [
  { value: 'main-hall-access', label: 'Main Hall Access' },
  { value: 'entry-badge', label: 'Entry Badge' },
  { value: 'meal-coupons', label: 'Meal Coupons' },
  { value: 'drink-vouchers', label: 'Drink Vouchers' },
  { value: 'merchandise-package', label: 'Merchandise Package' },
  { value: 'workshop-pass', label: 'Workshop Access Pass' },
  { value: 'vip-lounge', label: 'VIP Lounge Access' },
  { value: 'priority-seating', label: 'Priority Seating' },
  { value: 'meet-greet', label: 'Meet & Greet with Speakers' },
  { value: 'shuttle-service', label: 'Shuttle Service' },
  { value: 'exclusive-networking', label: 'Exclusive Networking Events' },
  { value: 'backstage-tour', label: 'Backstage Tour' },
  { value: 'certificate', label: 'Participation Certificate' },
  { value: 'early-checkin', label: 'Early Check-In' },
  { value: 'charging-station-access', label: 'Charging Station Access' },
  { value: 'guided-tour', label: 'Venue Guided Tour' },
  { value: 'photo-session', label: 'Photo Session Booth' },
  { value: 'eco-kit', label: 'Eco-Friendly Welcome Kit' },
  { value: 'recordings-access', label: 'Event Recordings Access' },
  { value: 'priority-support', label: 'Priority Customer Support' },
  { value: 'translation-device', label: 'Live Translation Device' },
  { value: 'tech-support', label: 'Technical Support Access' }
];